### ISSUE TITLE
Version 1.0.2 was released, but setup.py still mentions "1.0.1"

### ISSUE THREAD

**Issue by AlexandreDecan** [natarajan-chidambaram/RABBIT#31]
@natarajan-chidambaram do not forget to keep `setup.py` up-to-date with your releases. Currently, the file mentions `1.0.1` while there's a `1.0.2` release.

**Comment by natarajan-chidambaram** [comment]
Thank you, It is updated now. I will create a checklist to make sure all changes are inline when a release is made.
