### ISSUE TITLE
--verbose option

### ISSUE THREAD

**Issue by tommens** [natarajan-chidambaram/RABBIT#51]
**Is your feature request related to a problem? Please describe.**
In the current version of RABBIT (release 2), the --verbose option displays the "type" and "confidence" values at the end, after all more detailed metrics.

**Describe the solution you'd like**
 I would argue that it makes more sense to output the "type" and "confidence" values FIRST (before the other more detailed metrics), for two main reasons:
1. In that case, you can consider the --verbose option just as extending the table of results (e.g. if you output in a CSV format) by appending extra columns to the table that is outputted without the verbose option, rather than inserting some columns somewhere in between
2. Also, from a user point of view, it is more relevant to FIRST know what is the type and confidence, before seeing the detailed metrics. (Especially for those types for which the confidence is 1.0, since for them no additional metrics are provided by the verbose option.)

**Comment by natarajan-chidambaram** [comment]
Yes, it makes more sense this way. Thank you for suggesting this improvement @tommens. This will be part of RABBIT version 2.0.1.

**Comment by tommens** [comment]
Should become RABBIT release 2.1.0 rather than 2.0.1. Why? Because it is not simply a patch with a bug fix. The bug fix actually extends (in a conservative way, mostly, i.e. I do not expect breaking changes) the functionality of RABBIT in a way: before, rabbit was not able to detect organisation types, in the new version, it will. By extension, with the code change suggestions I have sent you by email, rabbit should be able to detect and return instantly with a confidence of 1.0 any contributor type that is not 'User' (by taking the type value from the Users API). Only for contributor types that are 'User' the classification model will come into play.
